# Generated by Django 4.1.5 on 2023-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nested_menu', '0002_alter_menu_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='url меню'),
        ),
    ]
